name: CI Tests

on:
  push:
    branches:
      - feat/test-gha-image-caching

jobs:
  cache-images:
    runs-on: ubuntu-latest
    steps:
      - name: Cache text files dir
        uses: actions/cache@v2
        env:
          cache-name: develop-text-files-dir-test
        with:
          path: ~/test-caching
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ env.cache-name }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.cache-name }}

      - name: Output to test cache dir
        run: |
          mkdir -p ~/test-caching
          date >> ~/test-caching/run_ids.txt
          echo "${{ github.run_id }}" >> ~/test-caching/run_ids.txt
          echo "${{ github.run_number }}" >> ~/test-caching/run_ids.txt
          echo "${{ github.ref }}" >> ~/test-caching/run_ids.txt
          echo "${{ github.sha }}\n" >> ~/test-caching/run_ids.txt



    # - name: Cache images dir
    #   uses: actions/cache@v2
    #   with:
    #     path: resources/_gen/images/
    #     # Look to see if there is a cache hit for the corresponding requirements file
    #     key: develop-images-cache-${{ github.run_id }}
    #     restore-keys: |
    #       develop-images-cache
    # - uses: actions/checkout@v2
    # - name: Set up Python
    #   uses: actions/setup-python@v2
    #   with:
    #     python-version: '3.10.x'
    #     architecture: 'x64'
    # - name: Cache pip
    #   uses: actions/cache@v2
    #   with:
    #     path: ~/.cache/pip
    #     # Look to see if there is a cache hit for the corresponding requirements file
    #     key: ${{ runner.os }}-pip-${{ hashFiles('./ci/requirements.txt') }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-
    #       ${{ runner.os }}-
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r ./ci/requirements.txt
    # - name: Use Node.js
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: '12.x'
    # - name: Install dependencies (Node)
    #   run: npm install
    # - name: Set up Hugo
    #   uses: peaceiris/actions-hugo@v2
    #   with:
    #     hugo-version: '0.83.1'
    # - name: Build Hugo
    #   run: hugo --gc
    # - name: Delete old image caches